name: Deploy Slidev
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    # 환경 변수에 Node.js 24 강제 사용 설정을 추가했습니다.
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24 # 노드 버전을 24로 올렸습니다.
      - run: npm install
      # 저장소 이름을 본인의 저장소명(sadongsae)으로 바꿔주세요!
      - run: npm run build -- --base /sadongsae/ 
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages